#!/bin/bash
# Checks that pg_statecharts installs into a database that already uses the
# `semver` extension.
#
# Before 0.1.0 moved its version handling into the fsm schema, both extensions
# defined to_semver(text) in the same schema and CREATE EXTENSION simply failed.
# Now everything of ours is fsm qualified, and the only unqualified object --
# the compatibility alias for migrations generated by 0.0.0 -- is skipped when
# the name is taken.
set -eu

PSQL="psql -v ON_ERROR_STOP=1 -X -q"

echo "--- installing pg_statecharts alongside semver ---"
$PSQL -c "drop database if exists coexist_check"
$PSQL -c "create database coexist_check"

# The output is captured so the WARNING can be asserted on. semver's own script
# does "SET client_min_messages TO warning" and never resets it, which happens
# to be the level we need anyway.
output=$($PSQL -d coexist_check 2>&1 <<'SQL'
create extension semver;
create extension pg_statecharts cascade;
SQL
)
echo "$output"

if ! grep -q 'skipping the pg_statecharts compatibility shim' <<<"$output"; then
  echo "error: expected a WARNING about the skipped compatibility shim" >&2
  exit 1
fi

echo "--- verifying both extensions still work ---"
$PSQL -d coexist_check <<'SQL'
do $check$
  declare
    latest text;
  begin
    -- semver's to_semver(text) has to be untouched, still returning its own type
    if (select pg_get_function_result(oid)::text
        from pg_proc
        where proname = 'to_semver'
          and pronamespace = 'public'::regnamespace) <> 'semver' then
      raise exception 'the semver extension''s to_semver(text) was overwritten';
    end if;

    -- and ours has to exist under its own name
    if (select pg_get_function_result(oid)::text
        from pg_proc
        where proname = 'to_semver'
          and pronamespace = 'fsm'::regnamespace) <> 'fsm.semver' then
      raise exception 'fsm.to_semver(text) is missing';
    end if;

    -- nothing of ours may have been created in the shim's place
    if exists (
      select 1 from pg_depend d
      join pg_extension e on e.oid = d.refobjid
      where d.refclassid = 'pg_extension'::regclass
        and e.extname = 'pg_statecharts'
        and d.objid = (select oid from pg_proc
                       where proname = 'to_semver'
                         and pronamespace = 'public'::regnamespace)
    ) then
      raise exception 'the shim was created even though the name was taken';
    end if;

    -- the runtime has to work end to end without the shim
    insert into fsm.statechart (name, version) values
      ('flow', fsm.to_semver('1.9')), ('flow', fsm.to_semver('1.10.0'));

    select version into latest from fsm.get_latest_statechart('flow');
    if latest <> '1.10.0' then
      raise exception 'get_latest_statechart returned %, expected 1.10.0', latest;
    end if;

    raise notice 'pg_statecharts and semver coexist';
  end;
$check$;
SQL

echo "--- verifying DROP EXTENSION leaves semver alone ---"
$PSQL -d coexist_check -c "drop extension pg_statecharts cascade"
$PSQL -d coexist_check <<'SQL'
do $check$
begin
  if to_regprocedure('to_semver(text)') is null then
    raise exception 'dropping pg_statecharts took the semver extension''s to_semver with it';
  end if;
  raise notice 'semver survived DROP EXTENSION pg_statecharts';
end;
$check$;
SQL

echo "all coexistence checks passed"
