services:
  postgres:
    restart: always
    build:
      context: .
      dockerfile: _dev/postgres.Dockerfile
    environment:
      - SQITCH_PAGER
    volumes:
      - .:/repo
      - ~/.sqitch:/root/.sqitch
    ports:
      - "5432:5432"
