-- A pure SQL replacement for the `semver` PGXN extension.
--
-- The only reason `semver` was ever a dependency is that `fsm.statechart`
-- needs a version column that sorts correctly. `semver` is a C extension, so
-- depending on it means every user needs a compiler and the PostgreSQL server
-- headers just to install pg_statecharts. A domain over text gets us the same
-- storage and the same textual representation with no build step at all.
--
-- Everything lives in the fsm schema. That matters for more than tidiness:
-- the `semver` extension defines its own to_semver(text) in the schema it is
-- installed into, so an unqualified to_semver(text) here would collide with
-- it and make `create extension pg_statecharts` fail outright in any database
-- that happens to use `semver` for unrelated reasons. The only unqualified
-- object is the compatibility shim at the bottom of this file, and it is
-- skipped when the name is already taken.
--
-- The one thing we lose is type level ordering: `order by version` on a text
-- domain is lexicographic, which would rank 1.9.0 above 1.10.0. Use
-- fsm.semver_sort_key() whenever versions need to be compared or ordered.

create domain fsm.semver as text
  check (value ~ '^\d+\.\d+\.\d+$');

comment on domain fsm.semver is $comment$
    A semantic version of the form <major>.<minor>.<patch>, e.g. '1.10.0'.

    Prerelease and build metadata suffixes (1.0.0-rc1, 1.0.0+build5) are not
    supported.

    Beware that this is a domain over text, so the default ordering is
    lexicographic and therefore wrong: '1.9.0' sorts after '1.10.0'. Order by
    fsm.semver_sort_key(version) instead.
$comment$;

create or replace function fsm.to_semver(version text)
returns fsm.semver as
$$
  declare
    dot_count integer;
    padded text;
  begin
    if version is null then
      return null;
    end if;

    dot_count := length(version) - length(replace(version, '.', ''));

    if dot_count > 2 then
      raise exception 'invalid version %', quote_literal(version)
        using hint = 'expected at most three components, e.g. 1.2.3';
    end if;

    -- pads with '.0' if the provided value has fewer than two dots, so that
    -- both '1' and '1.2' are accepted and normalised to '1.0.0' and '1.2.0'
    padded := version || repeat('.0', 2 - dot_count);

    if padded !~ '^\d+\.\d+\.\d+$' then
      raise exception 'invalid version %', quote_literal(version)
        using hint = 'expected digits separated by dots, e.g. 1.2.3';
    end if;

    return padded::fsm.semver;
  end;
$$ language plpgsql immutable;

comment on function fsm.to_semver(text) is $comment$
    Casts text to fsm.semver, padding out omitted components so that '1' and
    '1.2' become '1.0.0' and '1.2.0'.

    This is the canonical name. An unqualified to_semver(text) is also created
    when that name is free, for the benefit of statechart migrations generated
    against older versions of pg_statecharts.
$comment$;

create or replace function fsm.semver_sort_key(version fsm.semver)
returns integer[] as
$$
  select string_to_array(version, '.')::integer[]
$$ language sql immutable strict parallel safe;

comment on function fsm.semver_sort_key(fsm.semver) is $comment$
    Turns a version into an integer array so that it sorts numerically rather
    than lexicographically. Integer arrays compare element by element, and a
    shorter array sorts before a longer one that shares its leading elements,
    so '1.10.0' correctly sorts above '1.9.0'.

        order by fsm.semver_sort_key(version) desc

    The function is immutable, so it can also be used to build an index:

        create index on fsm.statechart (name, fsm.semver_sort_key(version));
$comment$;

-- Compatibility shim.
--
-- Statechart migrations generated by pg_statecharts 0.0.0 call an unqualified
-- to_semver(...), which back then resolved to the `semver` extension's
-- function. Creating one here keeps those migrations deploying, reverting and
-- verifying unchanged.
--
-- It is conditional because that is exactly the name `semver` occupies. If
-- something else already provides to_semver(text) we leave it alone and carry
-- on: a database that uses `semver` for its own purposes can still install
-- pg_statecharts, it just does not get the shim. Migrations generated from
-- 0.1.0 onwards call fsm.to_semver(...) and do not depend on it.
--
-- Objects created inside a DO block during CREATE EXTENSION are still
-- recorded as members of the extension, so this is dropped by DROP EXTENSION
-- like any other object here.
--
-- The skip is reported at WARNING rather than NOTICE deliberately: PostgreSQL
-- runs extension scripts with client_min_messages set to warning, so a NOTICE
-- here would never reach whoever ran CREATE EXTENSION.
do $shim$
  begin
    if exists (
      select 1
      from pg_proc p
      where p.proname = 'to_semver'
        and p.pronamespace = current_schema()::regnamespace
        and pg_get_function_identity_arguments(p.oid) = 'text'
    ) then
      raise warning 'to_semver(text) already exists in schema %, skipping the pg_statecharts compatibility shim', current_schema()
        using hint = 'use fsm.to_semver(text) instead; migrations generated by '
                     'pg_statecharts 0.0.0 will need regenerating';
      return;
    end if;

    create function to_semver(version text)
    returns fsm.semver as
    $body$
      select fsm.to_semver(version)
    $body$ language sql immutable;

    comment on function to_semver(text) is $c$
    Deprecated alias for fsm.to_semver(text), kept so that statechart
    migrations generated by pg_statecharts 0.0.0 keep working. Not created if
    the name was already taken, so do not rely on it in new code.
    $c$;
  end;
$shim$;
