-- A stand-in for the 0.0.0 (Rust/pgrx) install, used only to test the upgrade
-- to 0.1.0. It is not the whole of 0.0.0, just the parts the upgrade script
-- touches: the statechart table with its `semver` typed version column, and
-- the two functions that were C functions backed by pg_statecharts.so and have
-- since moved out to pg_statecharts_dev.
\echo Use "CREATE EXTENSION pg_statecharts" to load this file. \quit

create schema fsm;

create table fsm.statechart (
  id bigint not null generated by default as identity ( start with 1 cache 32767 ) primary key,
  created_at timestamptz not null default now(),
  name text not null,
  version semver not null,

  constraint name_must_be_within_bounds
    check (char_length(name) >= 1 and char_length(name) <= 200)
);

create unique index idx_unique_name_version on fsm.statechart(name, version);

-- Note the constraint: 0.0.0 really did ship '^[a-za-z0-9_]+$', with the A-Z
-- range flattened to a second a-z. The upgrade has to repair it.
create table fsm.state (
  statechart_id bigint not null,
  is_initial bool not null,
  is_final bool not null,
  id text not null,
  name text not null,
  parent_path ltree not null,
  node_path ltree not null,
  parent_id text,
  primary key (statechart_id, id),

  constraint id_must_be_alphanumeric
    check (id ~ '^[a-za-z0-9_]+$'),

  constraint fk_statechart
    foreign key(statechart_id)
    references fsm.statechart(id)
    on delete cascade
);

create function fsm.get_latest_statechart(named text)
returns setof fsm.statechart as
$$
    select *
    from fsm.statechart
    where name = named
    order by version desc
    limit 1
$$ language sql strict stable parallel safe rows 1;

create function fsm.import_scxml_files(
  source_path text, recursive bool, on_conflict_do_nothing bool
)
returns table (id bigint, created_at timestamptz, name text, version text)
language sql as
$$ select null::bigint, null::timestamptz, null::text, null::text limit 0 $$;

create function fsm.gen_statechart_sqitch_migrations(
  source_path text, sqitch_plan_file_path text, recursive bool, file_permission_666 bool
)
returns void language sql as $$ select $$;
