-- Upgrade from the Rust (pgrx) implementation to the pure SQL one.
--
--     alter extension pg_statecharts update;
--
-- Two things change:
--
--   1. The `version` column moves off the `semver` extension's type and onto
--      the fsm.semver domain, an integer array, so that nothing has to be
--      compiled to install pg_statecharts and versions still sort correctly.
--      The versions themselves are unchanged, but their representation is not:
--      a column that read '1.10.0' now reads '{1,10,0}'. Use
--      fsm.semver_text(version) to render one. The canonical cast is now
--      fsm.to_semver(), and an unqualified to_semver() is recreated once the
--      `semver` extension has released the name, so migrations generated by
--      earlier versions still deploy, revert and verify unchanged.
--
--   2. fsm.import_scxml_files and fsm.gen_statechart_sqitch_migrations move
--      out to the separate pg_statecharts_dev extension. They read and write
--      files on the database server, and there is no reason for that to be
--      installed in production. Install pg_statecharts_dev on the machines
--      that need them.
--
-- Once the upgrade has been applied nothing references pg_statecharts.so any
-- more, so it can be deleted from $(pg_config --pkglibdir).

\echo Use "ALTER EXTENSION pg_statecharts UPDATE" to load this file. \quit

-- The old file generating functions were C functions backed by pg_statecharts.so.
drop function if exists fsm.import_scxml_files(text, boolean, boolean);
drop function if exists fsm.gen_statechart_sqitch_migrations(text, text, boolean, boolean);

-- 0.0.0 shipped '^[a-za-z0-9_]+$' for this constraint: the A-Z range had been
-- flattened to a second a-z by a stray lowercasing, so state ids containing
-- capital letters were rejected even though the sqitch deployment of the same
-- schema accepted them. The corrected pattern only ever accepts more than the
-- old one did, so no existing row can fail the revalidation.
alter table fsm.state drop constraint if exists id_must_be_alphanumeric;
alter table fsm.state add constraint id_must_be_alphanumeric
  check (id ~ '^[a-zA-Z0-9_]+$');

-- Everything semver related lives in the fsm schema now, so that the only
-- thing competing with the `semver` extension for a name is the deliberate
-- compatibility shim at the end of this file.
create domain fsm.semver as integer[]
  check (array_ndims(value) = 1
         and array_lower(value, 1) = 1
         and cardinality(value) = 3
         and array_position(value, null) is null
         and value[1] >= 0
         and value[2] >= 0
         and value[3] >= 0);

comment on domain fsm.semver is $comment$
    A semantic version as a three element integer array: {major, minor, patch}.
    '1.10.0' is array[1, 10, 0].

    Stored as integers rather than text so that ordering is correct by default.
    Arrays compare element by element, so `order by version desc` ranks 1.10.0
    above 1.9.0 with no helper function involved.

    Build one with fsm.to_semver('1.10.0') and render one with
    fsm.semver_text(version). Casting to text gives the array form, '{1,10,0}'.

    Prerelease and build metadata suffixes (1.0.0-rc1, 1.0.0+build5) are not
    supported.
$comment$;

-- fsm.semver has no room for prerelease or build metadata suffixes, but 0.0.0
-- stored versions in the semver extension's type, which accepts 1.0.0-rc1 and
-- 1.0.0+build5 happily. Converting such a row would fail inside the ALTER
-- below with a bare "invalid input syntax for type integer", naming nothing.
-- Find them first and say which rows they are.
do $precheck$
  declare
    offending text;
  begin
    select string_agg(format('%s %s', name, version::text), E'\n' order by name, version::text)
    into offending
    from fsm.statechart
    where version::text !~ '^\d+\.\d+\.\d+$';

    if offending is not null then
      raise exception 'cannot upgrade: some statechart versions carry a prerelease or build suffix, which fsm.semver does not support'
        using detail = offending,
              hint = 'rename those versions to plain major.minor.patch first, e.g. '
                     'update fsm.statechart set version = to_semver(''1.0.0'') '
                     'where name = ''...'' and version = to_semver(''1.0.0-rc1''), '
                     'then run ALTER EXTENSION pg_statecharts UPDATE again';
    end if;
  end;
$precheck$;

-- Rewrites the column in place. The (name, version) unique index is rebuilt
-- automatically as part of the type change.
--
-- semver only offers an explicit cast to text, which is fine inside a USING
-- expression, and the check above means every stored value has exactly three
-- numeric components.
alter table fsm.statechart
  alter column version type fsm.semver
  using string_to_array(version::text, '.')::integer[]::fsm.semver;

do $upgrade$
  declare
    dependents text;
  begin
    if not exists (select 1 from pg_extension where extname = 'semver') then
      return;
    end if;

    -- CREATE EXTENSION ... CASCADE recorded pg_statecharts as depending on the
    -- semver extension. Nothing in pg_statecharts uses semver any more, but
    -- that catalog entry would still make DROP EXTENSION semver fail with
    -- "extension pg_statecharts depends on extension semver", so drop the edge.
    delete from pg_depend
    where classid = 'pg_extension'::regclass
      and objid = (select oid from pg_extension where extname = 'pg_statecharts')
      and refclassid = 'pg_extension'::regclass
      and refobjid = (select oid from pg_extension where extname = 'semver');

    -- Our own objects are all fsm qualified and would not collide, but the
    -- unqualified compatibility shim below can only be created once the semver
    -- extension has released the name, so semver genuinely has to go. If
    -- anything outside pg_statecharts still uses it we would rather fail loudly
    -- here than leave the database in a half migrated state.
    begin
      drop extension semver;
    exception when dependent_objects_still_exist then
      get stacked diagnostics dependents = pg_exception_detail;

      raise exception 'cannot remove the semver extension because it is still in use'
        using detail = dependents,
              hint = 'pg_statecharts no longer needs semver, but something else '
                     'in this database does. Migrate those objects to the '
                     'fsm.semver domain (or another type), then run '
                     'ALTER EXTENSION pg_statecharts UPDATE again.';
    end;
  end;
$upgrade$;

create or replace function fsm.to_semver(version text)
returns fsm.semver as
$$
  declare
    dot_count integer;
    padded text;
  begin
    if version is null then
      return null;
    end if;

    dot_count := length(version) - length(replace(version, '.', ''));

    if dot_count > 2 then
      raise exception 'invalid version %', quote_literal(version)
        using hint = 'expected at most three components, e.g. 1.2.3';
    end if;

    -- pads with '.0' if the provided value has fewer than two dots, so that
    -- both '1' and '1.2' are accepted and normalised to '1.0.0' and '1.2.0'
    padded := version || repeat('.0', 2 - dot_count);

    if padded !~ '^\d+\.\d+\.\d+$' then
      raise exception 'invalid version %', quote_literal(version)
        using hint = 'expected digits separated by dots, e.g. 1.2.3';
    end if;

    return string_to_array(padded, '.')::integer[]::fsm.semver;
  end;
$$ language plpgsql immutable;

comment on function fsm.to_semver(text) is $comment$
    Parses text into an fsm.semver, padding out omitted components so that '1'
    and '1.2' become 1.0.0 and 1.2.0.

    This is the canonical name. An unqualified to_semver(text) is also created
    when that name is free, for the benefit of statechart migrations generated
    against older versions of pg_statecharts.
$comment$;

create or replace function fsm.semver_text(version fsm.semver)
returns text as
$$
  select array_to_string(version, '.')
$$ language sql immutable strict parallel safe;

comment on function fsm.semver_text(fsm.semver) is $comment$
    Renders a version the way people write it: fsm.semver_text(array[1,10,0])
    is '1.10.0'. Casting to text instead gives the array form, '{1,10,0}'.
$comment$;

-- Compatibility shim, recreating the unqualified to_semver(text) that
-- migrations generated by 0.0.0 call. The `semver` extension owned that name
-- until the DO block above dropped it, so by this point it is normally free.
-- It is still guarded: an install that never had `semver` may have something
-- else of that name, and taking it would be wrong. See sql/type/semver.sql.
do $shim$
  begin
    if exists (
      select 1
      from pg_proc p
      where p.proname = 'to_semver'
        and p.pronamespace = current_schema()::regnamespace
        and pg_get_function_identity_arguments(p.oid) = 'text'
    ) then
      raise warning 'to_semver(text) already exists in schema %, skipping the pg_statecharts compatibility shim', current_schema()
        using hint = 'use fsm.to_semver(text) instead; migrations generated by '
                     'pg_statecharts 0.0.0 will need regenerating';
      return;
    end if;

    create function to_semver(version text)
    returns fsm.semver as
    $body$
      select fsm.to_semver(version)
    $body$ language sql immutable;

    comment on function to_semver(text) is $c$
    Deprecated alias for fsm.to_semver(text), kept so that statechart
    migrations generated by pg_statecharts 0.0.0 keep working. Not created if
    the name was already taken, so do not rely on it in new code.
    $c$;
  end;
$shim$;

-- Recreated only so that an upgraded database provably matches a fresh 0.1.0
-- install. The body is unchanged: "order by version desc" was already correct
-- under the semver type and is still correct over an integer array, because
-- both compare numerically rather than lexicographically.
create or replace function fsm.get_latest_statechart(named text)
returns setof fsm.statechart as
$$
    select *
    from fsm.statechart
    where name = named
    order by version desc
    limit 1
$$ language sql
    strict
    stable
    parallel safe
    rows 1;
