
-- set client_min_messages to warning;
--   create extension if not exists ltree;
-- reset client_min_messages;

create schema fsm;
comment on schema fsm is 'Schema containing the statecharts implementation.';

-- statechart tables
create table fsm.statechart (
  id bigint not null generated by default as identity ( start with 1 cache 32767 ) primary key,
  created_at timestamptz not null default now(),
  name text not null,
  version semver not null,

  constraint name_must_be_within_bounds
    check (char_length(name) >= 1 and char_length(name) <= 200)
);

create unique index idx_unique_name_version on fsm.statechart(name, version);

comment on table fsm.statechart is 'All the different statecharts and their versions.';

create type fsm_callback_name as (
  schema_name name,
  function_name name
);

comment on type fsm_callback_name is
    'Type for on_entry and on_exit callbacks. Should contain both the schema and the function name to invoke';

create table fsm.state (
  statechart_id bigint not null,
  is_initial bool not null,
  is_final bool not null,
  id text not null,
  name text not null,
  parent_path ltree not null,
  node_path ltree not null,
  parent_id text,
  on_entry fsm_callback_name[] not null default array[]::fsm_callback_name[],
  on_exit fsm_callback_name[] not null default array[]::fsm_callback_name[],
  primary key (statechart_id, id),

  constraint id_must_be_within_bounds
    check (char_length(id) >= 1 and char_length(id) <= 50),

  constraint id_must_be_alphanumeric
    check (id ~ '^[a-zA-Z0-9_]+$'),

  constraint cannot_be_both_initial_and_final
    check (not (is_initial and is_final)),

  constraint fk_statechart
    foreign key(statechart_id)
    references fsm.statechart(id)
    on delete cascade,

  constraint fk_parent_state
    foreign key(statechart_id, parent_id)
    references fsm.state(statechart_id, id)
    on delete cascade
);

create index idx_parent on fsm.state(statechart_id, parent_id);
create index idx_parent_path on fsm.state using gist (parent_path) include (statechart_id);
create index idx_node_path on fsm.state using gist (node_path) include (statechart_id);

-- https://statecharts.dev/glossary/state.html
comment on table fsm.state is $comment$
    A state in a state machine describes a particular behaviour of the machine.
    When we say that a machine is “in” a state, it means that the machine behaves
    in the way that state describes.

    The behaviour of a state is defined as how the state reacts to events.
    Each state can specify a number of events that it “understands”, and specifies,
    for each event, any number of transitions that could be taken, if that event happens.
    A state also describes a set of actions to execute when the state is entered or
    exited, and in some implementations, activities that should be happening for the
    entire duration of time that the machine is in the state.

    When a state machine is executed, it enters the initial state, and adopts the
    behaviour associated with that state.  As the machine handles events, it
    transitions to other states, thus changing the behaviour of the machine over time.
$comment$;

-- https://statecharts.dev/glossary/initial-state.html
comment on column fsm.state.is_initial is $comment$
    The initial state in the state machine. There can only be one initial state
    in a state machine, but there can be many for parallel states.

    When a state machine starts, it starts by entering the machine’s initial state.
    Likewise, when a compound state is entered, its initial state is also entered.
    The initial state is not a separate state, but more like an indication of which
    state that the machine should start in by default.

    An initial state should be thought of as the default starting point of a compound state
    if a transition points directly to the compound state.
$comment$;

-- https://statecharts.dev/glossary/final-state.html
comment on column fsm.state.is_final is $comment$
    The final state in the state machine. There cannot be any transitions from
    the final state.

    A final state is a state in a compound state that designates that the compound
    state in question has completed, i.e. will not process any further events.
    Reaching a final state will generate an internal event, which in turn can allow
    other parts of the state machine to react to the fact that the compound state has
    “completed”.
$comment$;

comment on column fsm.state.parent_path is $comment$
    Parent path of the state. This is used to represent that a state is a
    child state, or part of a parallel state.

    This column is automatically set based on the "parent_id" column.
$comment$;

comment on column fsm.state.node_path is $comment$
    Path of the state that is represented from the root of the tree.

    This column is automatically set based on the "parent_id" column.
$comment$;

comment on column fsm.state.parent_id is $comment$
    Id of the parent state.
    NULL means that the state has no parent, i.e. it is not part of a composite
    nor parallel state.
$comment$;

comment on column fsm.state.on_entry is $comment$
    The functions to execute when this state is entered.
$comment$;

comment on column fsm.state.on_exit is $comment$
    The functions to execute when the state is exited.
$comment$;


-- transition table 
create table fsm.transition (
  statechart_id bigint not null,
  event text not null,
  source_state text not null,
  target_state text not null,
  primary key (statechart_id, event, source_state),

  constraint event_must_be_within_bounds
    check (char_length(event) >= 1 and char_length(event) <= 100),

  constraint fk_source_state
    foreign key(statechart_id, source_state)
    references fsm.state(statechart_id, id)
    on delete cascade,

  constraint fk_target_state
    foreign key(statechart_id, target_state)
    references fsm.state(statechart_id, id)
    on delete cascade
);

-- https://statecharts.dev/glossary/transition.html
comment on table fsm.transition is $comment$
    In an executing state machine, a transition is the instantaneous transfer
    from one state to another.  In a state machine, a transition tells us
    what happens when an event occurs.

    When an event happens, the currently active state(s) are inspected,
    looking for an outbound transition that could be triggered by the event.
$comment$;

comment on column fsm.transition.event is 'Name of the transition event.';

comment on column fsm.transition.source_state is 'The from state of the transition.';

comment on column fsm.transition.target_state is 'The to state of the transition.';

-- check_no_cross_boundary_transition trigger
create or replace function fsm.trig_check_no_cross_boundary_transition() returns trigger as
$$
  declare
      bad_transitions jsonb;
  begin
    select jsonb_agg(c.*) into bad_transitions
    -- changed is the table of changes that where just modified
    from changed c
    join fsm.state source
      on  source.statechart_id = c.statechart_id
      and source.id = c.source_state
    join fsm.state target
      on  target.statechart_id = c.statechart_id
      and target.id = c.target_state
    where source.parent_id <> target.parent_id;

    if jsonb_array_length(bad_transitions) > 0
    then
      raise exception 'cannot add transitions between states with different parents: %', jsonb_pretty(bad_transitions);
    end if;

    return null;
  end;
$$ language plpgsql;

comment on function fsm.trig_check_no_cross_boundary_transition is $comment$
    This function checks that there are no transitions between states with
    different parents in the "fsm.transition" table.
$comment$;

set client_min_messages TO warning;
drop trigger if exists check_no_cross_boundary_transitions_insert on fsm.transition;
drop trigger if exists check_no_cross_boundary_transitions_update on fsm.transition;
reset client_min_messages;

create trigger check_no_cross_boundary_transitions_insert
after insert
on fsm.transition
referencing new table as changed
for each statement
execute function fsm.trig_check_no_cross_boundary_transition();

comment on trigger check_no_cross_boundary_transitions_insert on fsm.transition is $comment$
    Checks that no transitions in between states with different parents are
    inserted in the "fsm.transition" table.
$comment$;

create trigger check_no_cross_boundary_transitions_update
after update
on fsm.transition
referencing new table as changed
for each statement
execute function fsm.trig_check_no_cross_boundary_transition();

comment on trigger check_no_cross_boundary_transitions_update on fsm.transition is $comment$
    Checks that no transitions in between states with different parents are
    inserted in the "fsm.transition" table.
$comment$;

-- check_no_duplicate_event_handler trigger
create or replace function fsm.trig_check_no_duplicate_event_handler() returns trigger as
$$
  declare
      duplicate_transitions jsonb;
  begin
    with changed_event as (
      select distinct statechart_id, event
      from changed
    )
    -- look at the entire tree to see if the same event name is used
    -- for a transition
    select jsonb_agg(t.*) into duplicate_transitions
    from fsm.transition t
    -- need to get the source state info for the transition
    -- specifically, we need to get its node_path
    join fsm.state s
      on  s.statechart_id = t.statechart_id
      and s.id = t.source_state
    -- get all children and parents on the source_state by using the node_path
    -- it is the count of this children nodes that will determine
    -- if the same event is used in another transition
    join fsm.state relative
      on  relative.statechart_id = t.statechart_id
      and (relative.node_path <@ s.node_path or relative.node_path @> s.node_path)
      and relative.id <> s.id
    join fsm.transition ct
      on  ct.statechart_id = relative.statechart_id
      and ct.source_state = relative.id
    join changed_event ce
      on  ce.statechart_id = ct.statechart_id
      and ce.event = ct.event
      and ce.statechart_id = t.statechart_id
      and ce.event = t.event;

    if jsonb_array_length(duplicate_transitions) > 0
    then
      raise exception $m$
      Cannot use the same event name for multiple transations in the same tree: %
      $m$, jsonb_pretty(duplicate_transitions);
    end if;

    return null;
  end;
$$ language plpgsql;

set client_min_messages TO warning;
drop trigger if exists check_no_duplicate_event_handler_insert on fsm.transition;
drop trigger if exists check_no_duplicate_event_handler_update on fsm.transition;
reset client_min_messages;

create trigger check_no_duplicate_event_handler_insert
after insert
on fsm.transition
referencing new table as changed
for each statement
execute function fsm.trig_check_no_duplicate_event_handler();

create trigger check_no_duplicate_event_handler_update
after update
on fsm.transition
referencing new table as changed
for each statement
execute function fsm.trig_check_no_duplicate_event_handler();

-- check_no_transition_for_final trigger
create or replace function fsm.trig_check_no_transition_for_final() returns trigger as
$$
  declare
      bad_transitions jsonb;
  begin
    select jsonb_agg(c.*) into bad_transitions
    from changed c
    join fsm.state s
      on  s.statechart_id = c.statechart_id
      and s.id = c.source_state
      and s.is_final;

    if jsonb_array_length(bad_transitions)
    then
      raise exception 'cannot add transitions from final states: %', jsonb_pretty(bad_transitions);
    end if;

    return null;
  end;
$$ language plpgsql;

comment on function fsm.trig_check_no_transition_for_final is $comment$
    Checks that there are no transitions added from final states.
$comment$;

-- create a similar function for states
create or replace function fsm.trig_check_no_final_state_with_transition() returns trigger as
$$
  declare
      bad_states jsonb;
  begin
    select jsonb_agg(c.*) into bad_states
    from changed c
    join fsm.transition t
      on  t.statechart_id = c.statechart_id
      and t.source_state = c.id
    where c.is_final;

    if jsonb_array_length(bad_states)
    then
      raise exception 'cannot add states with transitions from final states: %', jsonb_pretty(bad_states);
    end if;

    return null;
  end;
$$ language plpgsql;

comment on function fsm.trig_check_no_final_state_with_transition is $comment$
    Checks that there are no states added which have transitions from final states.
$comment$;

set client_min_messages TO warning;
drop trigger if exists check_no_transition_for_final_insert on fsm.transition;
drop trigger if exists check_no_transition_for_final_update on fsm.transition;
drop trigger if exists check_no_transition_for_final_update on fsm.state;
reset client_min_messages;

create trigger check_no_transition_for_final_insert
after insert
on fsm.transition
referencing new table as changed
for each statement
execute function fsm.trig_check_no_transition_for_final();

comment on trigger check_no_transition_for_final_insert on fsm.transition is $comment$
    Checks that there are no transitions inserted from final states.
$comment$;

create trigger check_no_transition_for_final_update
after update
on fsm.transition
referencing new table as changed
for each statement
execute function fsm.trig_check_no_transition_for_final();

comment on trigger check_no_transition_for_final_update on fsm.transition is $comment$
    Checks that there are no transitions added from final states.
$comment$;

create trigger check_no_transition_for_final_update
after update
on fsm.state
referencing new table as changed
for each statement
execute function fsm.trig_check_no_final_state_with_transition();

comment on trigger check_no_transition_for_final_update on fsm.transition is $comment$
    Checks that there are no states inserted with transitions from final states.
$comment$;

-- state machine tables
create table fsm.state_machine (
  shard_id bigint not null,
  id bigint not null generated by default as identity ( start with 1 cache 32767 ),
  statechart_id bigint not null,
  created_at timestamptz not null default now(),

  primary key (shard_id, id),

  constraint fk_statechart
    foreign key(statechart_id)
    references fsm.statechart(id)
    on delete cascade
);

create index idx_statechart on fsm.state_machine(statechart_id);

comment on table fsm.state_machine is
    'Runtime information of a statechart. Contains state machine instances that have started.';

create table fsm.state_machine_state (
  shard_id bigint not null,
  state_machine_id bigint not null,
  statechart_id bigint not null,
  entered_at timestamptz not null default now(),
  exited_at timestamptz,
  state_id text not null,

  constraint entered_should_be_before_exited
    check (entered_at <= exited_at),

  constraint fk_state_machine
    foreign key(shard_id, state_machine_id)
    references fsm.state_machine(shard_id, id)
    on delete cascade,

  constraint fk_state
    foreign key(statechart_id, state_id)
    references fsm.state(statechart_id, id)
    on delete cascade
);

create unique index idx_state on fsm.state_machine_state(shard_id, state_machine_id, state_id)
  where exited_at is null;

comment on table fsm.state_machine_state is $comment$
  Contains a log of the states that have been activated by a given state machine and
  is used to determine which states are currently active.
$comment$;

comment on column fsm.state_machine_state.entered_at is $comment$
    The timestamp when the state machine has transitioned to this state.
    This is the column that indicates that a state is currently active
    for a state machine.
    Should be before exited_at.
$comment$;

comment on column fsm.state_machine_state.exited_at is $comment$
    The timestamp when the state machine has transitioned away from this state.
    Should be after entered_at.
$comment$;

create table fsm.state_machine_event (
  shard_id bigint not null,
  id bigint not null generated by default as identity ( start with 1 cache 32767 ),
  state_machine_id bigint not null,
  created_at timestamptz not null default now(),
  handled_at timestamptz,
  name text not null,
  data jsonb not null,

  primary key (shard_id, id),

  constraint created_should_be_before_handled
    check (created_at <= handled_at),

  constraint fk_state_machine
    foreign key(shard_id, state_machine_id)
    references fsm.state_machine(shard_id, id)
    on delete cascade
);

create index idx_state_machine on fsm.state_machine_event(shard_id, state_machine_id)
  where handled_at is null;

comment on table fsm.state_machine_event is
    'Queue of events that need to be processed for the state machine.';

comment on column fsm.state_machine_event.created_at is $comment$
    The timestamp when this event was created. The timestamp should be
    before "handled_at".
$comment$;

comment on column fsm.state_machine_event.handled_at is $comment$
    The timestamp when this event was handled. The timestamp should be
    after "created_at".
$comment$;

comment on column fsm.state_machine_event.data is $comment$
     The data to be sent to the callback handlers in on_entry, on_exit.
$comment$;

-- check_no_state_loops_trigger
create or replace function fsm.trig_check_no_state_loops()
returns trigger as
$$
declare the_cycle text[];
begin

  with recursive chart as (
    select distinct statechart_id
    from changed
  )
  , prev as (
    select cs.statechart_id, cs.id, array[id] as seen, false as cycle
    from fsm.state cs
    join chart
      on  chart.statechart_id = cs.statechart_id
    where parent_id is null

    union all

    select cs.statechart_id, cs.id, seen || cs.id as seen,
        cs.id = any(seen) as cycle
    from prev
    join fsm.state cs
      on  cs.statechart_id = prev.statechart_id
      and cs.parent_id = prev.id
      and prev.cycle = false
    join chart
      on  chart.statechart_id = cs.statechart_id
  )
  select seen into the_cycle
  from prev
  where prev.cycle
  limit 1;

  if the_cycle is not null
  then
    raise exception 'compound states should form a directed graph. Cycle detected: %', the_cycle;
  end if;

  return null;
end;
$$ language plpgsql;

comment on function fsm.trig_check_no_state_loops is $comment$
    Checks that the compound states do not form a cycle. Compound states
    should form a directed graph.
$comment$;

set client_min_messages TO warning;
drop trigger if exists check_no_state_loops_insert on fsm.state;
drop trigger if exists check_no_state_loops_update on fsm.state;
reset client_min_messages;

create trigger check_no_state_loops_insert
after insert
on fsm.state
referencing new table as changed
for each statement
execute function fsm.trig_check_no_state_loops();

comment on trigger check_no_state_loops_insert on fsm.state is $comment$
    Checks that the compound states do not form a cycle. Compound states
    should form a directed graph.
$comment$;

create trigger check_no_state_loops_update
after update
on fsm.state
referencing new table as changed
for each statement
execute function fsm.trig_check_no_state_loops();

comment on trigger check_no_state_loops_update on fsm.state is $comment$
    Checks that the compound states do not form a cycle. Compound states
    should form a directed graph.
$comment$;

-- check_valid_initial_state trigger
create or replace function fsm.trig_check_valid_initial_state() returns trigger as
$$
  declare
      chart bigint;
      total_initial bigint;
  begin
    for chart in
      select distinct statechart_id
      from changed
      where exists (select 1 from fsm.statechart where id = changed.statechart_id)
    loop
        select count(*) into total_initial
        from fsm.state
        where statechart_id = chart
          and is_initial
          and parent_id is null;

        if total_initial is distinct from 1
        then
          raise exception 'exactly one initial state is required per statechart';
        end if;

    end loop;

    return null;
  end;
$$ language plpgsql;

comment on function fsm.trig_check_valid_initial_state is $comment$
    Checks that there is only initial state per statechart. Only considers
    initial states whose parent_id is null.
$comment$;

set client_min_messages TO warning;
drop trigger if exists check_valid_initial_state_insert on fsm.state;
drop trigger if exists check_valid_initial_state_update on fsm.state;
drop trigger if exists check_valid_initial_state_delete on fsm.state;
reset client_min_messages;

create trigger check_valid_initial_state_insert
after insert
on fsm.state
referencing new table as changed
for each statement
execute function fsm.trig_check_valid_initial_state();

comment on trigger check_valid_initial_state_insert on fsm.state is $comment$
    Checks that there is only initial state per statechart. Only considers
    initial states whose parent_id is null.
$comment$;

create trigger check_valid_initial_state_update
after update
on fsm.state
referencing new table as changed
for each statement
execute function fsm.trig_check_valid_initial_state();

comment on trigger check_valid_initial_state_update on fsm.state is $comment$
    Checks that there is only initial state per statechart. Only considers
    initial states whose parent_id is null.
$comment$;

create trigger check_valid_initial_state_delete
after delete
on fsm.state
referencing old table as changed
for each statement
execute function fsm.trig_check_valid_initial_state();

comment on trigger check_valid_initial_state_delete on fsm.state is $comment$
    Checks that there is only initial state per statechart. Only considers
    initial states whose parent_id is null.
$comment$;
-- notify_machine_event trigger
create or replace function fsm.trig_notify_machine_event() returns trigger as
$$
  declare
    event record;
  begin

    for event in select distinct shard_id, state_machine_id from new
    loop
      perform fsm.handle_machine_events(event.shard_id, event.state_machine_id);
    end loop;

    return null;
  end;
$$ language plpgsql;

comment on function fsm.trig_notify_machine_event is $comment$
  Handles all of the newly inserted events for all affected state machines.
$comment$;

set client_min_messages TO warning;
drop trigger if exists notify_machine_event on fsm.state_machine_event;
reset client_min_messages;

create trigger notify_machine_event
after insert
on fsm.state_machine_event
referencing new table as new
for each statement
execute function fsm.trig_notify_machine_event();

comment on trigger notify_machine_event on fsm.state_machine_event is $comment$
  Handles all of the newly inserted events for all affected state machines.
$comment$;

-- set_state_parent_path trigger
create or replace function fsm.trig_set_state_parent_path() returns trigger as
$$
    declare
        path ltree;
    begin

        if NEW.parent_id is null then
            NEW.parent_path = coalesce(NEW.statechart_id, OLD.statechart_id)::text::ltree;

        elseif TG_OP = 'INSERT' or OLD.parent_id is null or OLD.parent_id != NEW.parent_id then
            select parent_path || id
            from fsm.state
            where id = NEW.parent_id and statechart_id = NEW.statechart_id and not is_final
            into path;

            if path is null then
                raise exception 'Invalid parent_id. It should exist and not be final: %', NEW.parent_id;
            end if;

            new.parent_path = path;
        end if;

        new.node_path = new.parent_path || new.id;

        return new;
    end;
$$ language plpgsql;

create trigger set_state_parent_path
    before insert or update on fsm.state
    for each row execute procedure fsm.trig_set_state_parent_path();
