name: statechart-sdk
version: 0.1.1.1
license: AllRightsReserved
author: "Kronor.io"
maintainer: "dev@kronor.io"
copyright: "2021 Kronor"

description: Statechart SDK (Statechart definitions and build tool)

default-extensions:
  - NoImplicitPrelude
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeFamilies
  - TypeApplications
  - TypeSynonymInstances
  - ViewPatterns
  - QuasiQuotes

dependencies:
  - base >= 4.11 && < 10
  - path
  - path-io
  - rio >= 0.1.12.0
  - string-interpolate
  - template-haskell

library:
  source-dirs:
    - src
  ghc-options:
    - -Wall
  dependencies:
    - xml-conduit
    - casing
    - containers
    - bytestring
    - text
    - aeson

tests:
  statechart-sdk-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - statechart-sdk
      - sydtest
      - sydtest-discover
      - directory
      - file-embed
