on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - master

name: Tests
permissions:
  contents: read

jobs:
  migrations:
    name: Migrations
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
    - name: Checkout
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      with:
        persist-credentials: false

    - name: Build Database
      run: |
        set -ex
        docker compose up -d postgres
        _dev/wait_for.sh 5432
        timeout 1m _dev/wait_for_migrations.sh
        docker compose exec -T postgres sqitch verify

    - name: Run Tests
      run: |
        docker compose exec -T postgres pg_prove test/
